### ISSUE TITLE
CINF and CLS returns wrong time

### ISSUE THREAD

**Issue by 4l4R1** [CasparCG/media-scanner#70]
According to the documentation, CINF and CLS should give the last modified time of the file.
This is not the case now.

I may be get its wrong, but the scanner.ts function scanFile gets from the file:
`doc.mediaTime = mediaStat.mtime.getTime()`

But in the function generateCinf returns
`moment(doc.thumbTime).format('YYYYMMDDHHmmss')`

Shouldn't it be doc.mediaTime as in function generateMediainfo?

**Comment by Julusian** [comment]
Thanks for reporting this
It has been fixed by https://github.com/CasparCG/media-scanner/commit/f6958379aaa9460c60e2ecaa6a14cc14a2731a55#diff-cd98925a2cc62595a508ce6f147cbab6878794d7067403cdbe75d11223b24116 and will be in the next release.

Be aware that the database will need deleting and regenerating for it to report the correct times for existing clips
